package aws.s3;

@:enum abstract S3Errors(Int) from Int to Int {
	var INCOMPLETE_SIGNATURE = 0;
	var INTERNAL_FAILURE = 1;
	var INVALID_ACTION = 2;
	var INVALID_CLIENT_TOKEN_ID = 3;
	var INVALID_PARAMETER_COMBINATION = 4;
	var INVALID_QUERY_PARAMETER = 5;
	var INVALID_PARAMETER_VALUE = 6;
	var MISSING_ACTION = 7; // SDK should never allow
	var MISSING_AUTHENTICATION_TOKEN = 8; // SDK should never allow
	var MISSING_PARAMETER = 9; // SDK should never allow
	var OPT_IN_REQUIRED = 10;
	var REQUEST_EXPIRED = 11;
	var SERVICE_UNAVAILABLE = 12;
	var THROTTLING = 13;
	var VALIDATION = 14;
	var ACCESS_DENIED = 15;
	var RESOURCE_NOT_FOUND = 16;
	var UNRECOGNIZED_CLIENT = 17;
	var MALFORMED_QUERY_STRING = 18;
	var NETWORK_CONNECTION = 99;
	var UNKNOWN = 100;

	var BUCKET_ALREADY_EXISTS = 129;
	var BUCKET_ALREADY_OWNED_BY_YOU = 130;
	var NO_SUCH_BUCKET = 131;
	var NO_SUCH_KEY = 132;
	var NO_SUCH_UPLOAD = 133;
	var OBJECT_ALREADY_IN_ACTIVE_TIER = 134;
	var OBJECT_NOT_IN_ACTIVE_TIER = 135;
}