language: haxe

haxe:
  - 3.2.1
  - development

os:
  - linux
  - osx

sudo: required
dist: trusty

install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update && brew upgrade cmake;
    fi;
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get update;
      sudo apt-get install uuid-dev -y;
    fi;
  - mkdir ~/haxelib && haxelib setup ~/haxelib;
  - cmake --version
  - cmake .
  - cmake --build .

script:
  - ctest -V
