language: haxe

haxe:
  - 3.2.1
  - development

os:
  - linux
  - osx

sudo: required
dist: trusty

install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update && brew upgrade cmake;
    fi;
  - mkdir ~/haxelib && haxelib setup ~/haxelib;
  - cmake --version
  - cmake .
  - make

script:
  - make test ARGS="-V"
