language: cpp

os:
  - linux
  - osx

sudo: required
dist: trusty

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo add-apt-repository ppa:haxe/releases -y &&
      sudo apt-get update &&
      sudo apt-get install haxe=1:3.2.1* neko-dev -y;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update && brew install haxe neko;
    fi;
  - mkdir ~/haxelib && haxelib setup ~/haxelib;
  - cmake --version
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      cmake .;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 .;
    fi;
  - make

script:
  - make test ARGS="-V"
