version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib
  matrix:
    - VisualStudioVersion: 12.0
      CMAKE_GENERATOR: "Visual Studio 12 2013"

install:
  # Checkout aws-sdk-cpp submodule
  - git submodule update --init --recursive
  # Install Haxe and Neko
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst haxe -version 3.2.1 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  - haxelib install all --always
  - haxelib list

build_script:
  - cmake -G "%CMAKE_GENERATOR%" .
  - cmake --build .

test_script:
  - ctest -C Debug -V

artifacts:
  - path: bin/*.ndll
