version: "{build}"

environment:
  matrix:
    - VisualStudioVersion: 12.0
      CMAKE_GENERATOR: "Visual Studio 12 2013"

platform: Win32
configuration: Release

install:
  # Checkout aws-sdk-cpp submodule
  - git submodule update --init --recursive
  # Install Haxe and Neko
  - cinst haxe -version 3.2.1 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"

build_script:
  - cmake -G "%CMAKE_GENERATOR%" .
  - cmake --build .

test: off