name: CI

on:
  push:
  workflow_dispatch:

env:
  EARTHLY_USE_INLINE_CACHE: "true"
  EARTHLY_SAVE_INLINE_CACHE: "true"
  FORCE_COLOR: 1

jobs:
  build-Linux64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: earthly/actions-setup@v1
        with:
          version: "v0.6.15"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build devcontainer
        run: earthly +ci-devcontainer --GIT_REF_NAME="${{ github.ref_name }}" --GIT_SHA="${{ github.sha }}"
        env:
          EARTHLY_PUSH: "${{ github.repository_owner == 'andyli' && github.event_name == 'push' }}"
      - name: Build
        run: earthly --artifact +build/aws.ndll bin/aws.ndll
      - name: Package
        run: earthly +ci-package-zip --GIT_REF_NAME="${{ github.ref_name }}" --GIT_SHA="${{ github.sha }}"
        env:
          EARTHLY_PUSH: "${{ github.repository_owner == 'andyli' && github.event_name == 'push' }}"
      - uses: actions/upload-artifact@v2
        with:
          name: ndll-Linux64
          path: bin/aws.ndll
  build-Windows64:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: choco install neko --version 2.3.0 --no-progress -y
      - run: choco install haxe --version 4.2.4 --no-progress -y
      - name: Prepend Chocolatey path
        run: echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Set NEKOPATH
        run: echo "NEKOPATH=C:\ProgramData\chocolatey\lib\neko\neko-2.3.0-win64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - run: haxelib newrepo
      - run: haxelib install all --always
      - run: cmake -G "Visual Studio 15 2017 Win64" .
      - run: cmake --build .
      - uses: actions/upload-artifact@v2
        with:
          name: ndll-Windows64
          path: bin/aws.ndll
