name: CI

on:
  push:
  workflow_dispatch:

env:
  EARTHLY_BUILDKIT_HOST: tcp://earthly:8372
  EARTHLY_USE_INLINE_CACHE: "true"
  EARTHLY_SAVE_INLINE_CACHE: "true"
  FORCE_COLOR: 1

jobs:
  build-Linux64:
    runs-on: ubuntu-latest
    container: ghcr.io/andyli/aws_sdk_neko_devcontainer:master
    services:
      earthly:
        image: earthly/buildkitd:v0.6.4
        options: --privileged
        env:
          BUILDKIT_TCP_TRANSPORT_ENABLED: "true"
        ports:
          - 8372
        volumes:
          - /tmp/earthly
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build devcontainer
        run: earthly +ci-devcontainer --GIT_REF_NAME="${{ github.ref_name }}" --GIT_SHA="${{ github.sha }}"
        env:
          EARTHLY_PUSH: "${{ github.repository_owner == 'andyli' && github.event_name == 'push' }}"
      - name: Build
        run: earthly --artifact +build/aws.ndll bin/aws.ndll
      - uses: actions/upload-artifact@v2
        with:
          name: ndll-Linux64
          path: bin/aws.ndll
